In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
import pickle

/usr/local/lib/python2.7/dist-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/usr/local/lib/python2.7/dist-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/usr/local/lib/python2.7/dist-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/usr/local/lib/python2.7/dist-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/usr/local/lib/python2.7/dist-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate bi

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/coordinate_descent.py:29: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import cd_fast
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/__init__.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sgd_fast import Hinge, Log, ModifiedHuber, SquaredLoss, Huber
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/sag.py:12: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sag_fast import sag
/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/gradient_boosting.py:34

In [2]:
data = pd.read_csv('lung_cancer.csv', index_col=False)
data = data.dropna()
data.head()


inst  time  status  age  sex  ph.ecog  ph.karno  pat.karno  meal.cal  \
1   3.0   455       2   68    1      0.0      90.0       90.0    1225.0   
3   5.0   210       2   57    1      1.0      90.0       60.0    1150.0   
5  12.0  1022       1   74    1      1.0      50.0       80.0     513.0   
6   7.0   310       2   68    2      2.0      70.0       60.0     384.0   
7  11.0   361       2   71    2      2.0      60.0       80.0     538.0   

   wt.loss  
1     15.0  
3     11.0  
5      0.0  
6     10.0  
7      1.0

In [3]:
Y = data['status'].values
X = data.drop('status', axis=1).values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=0)
print X_train

[[  11.  196.   42. ...   80. 1425.    8.]
 [  12.  223.   48. ...   80. 1300.   68.]
 [  22.  814.   65. ...   60.  513.   28.]
 ...
 [  13.  740.   44. ...   80.  588.   39.]
 [  11.  292.   69. ...   70. 2450.   36.]
 [   3.   65.   68. ...   50.  825.    8.]]


In [4]:
classifiers = [
    LogisticRegression(),
    KNeighborsClassifier(3),
    QuadraticDiscriminantAnalysis(),
    DecisionTreeClassifier(),
    LinearDiscriminantAnalysis(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GaussianNB(),
    GradientBoostingClassifier(),
    SVC(probability=True)
]

In [5]:
classifiers_names = [
    "Logistic Regression: ",
    "K Neighbors Classifier: ",
    "Quadratic Discriminant Analysis: ",
    "Decision Tree Classifier: ",
    "Linear Discriminant Analysis: ",
    "Random Forest Classifier: ",
    "Ada Boost Classifier: ",
    "Gaussian NB: ",
    "Gradient Boosting Classifier: ",
    "SVC: "
]

In [6]:
for clf in range(0, len(classifiers)):
    classifiers[clf].fit(X_train, Y_train)
    accuracy = accuracy_score(Y_test, classifiers[clf].predict(X_test))
    print classifiers_names[clf], round(accuracy,3)

Logistic Regression:  0.735
K Neighbors Classifier:  0.588
Quadratic Discriminant Analysis:  0.647
Decision Tree Classifier:  0.794
Linear Discriminant Analysis:  0.706
Random Forest Classifier:  0.735
Ada Boost Classifier:  0.765
Gaussian NB:  0.706
Gradient Boosting Classifier:  0.735
SVC:  0.706


In [7]:
model = DecisionTreeClassifier().fit(X_train, Y_train)
accuracy = accuracy_score(Y_test, model.predict(X_test))
print accuracy

0.7941176470588235


In [ ]:
filename = 'finalized_model_lung_cancer_prediction.sav'
pickle.dump(model, open(filename, 'wb'))